# Generated by Django 4.2.16 on 2026-06-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
