# Generated by Django 4.2.16 on 2026-06-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_password_reset_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_code_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_code_expires_at',
        ),
    ]
