# Generated by Django 4.2.7 on 2026-05-18 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reinvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(choices=[('new_stock', 'New Stock'), ('equipment', 'Equipment'), ('marketing', 'Marketing'), ('expansion', 'Expansion'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('expected_margin', models.DecimalField(decimal_places=2, default=0, help_text='Expected profit margin percentage', max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinvestments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reinvestments',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose'], name='reinvestmen_user_id_c9c135_idx'), models.Index(fields=['date'], name='reinvestmen_date_5107f6_idx')],
            },
        ),
    ]
