# Generated by Django 4.2.16 on 2026-08-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_barcode_product_products_barcode_d008ac_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pcs', help_text='Unit the product is sold in, e.g. pcs, kg, heap, pack, bundle, box, litre, dozen', max_length=20),
        ),
    ]
