# Generated by Django 4.2.7 on 2026-06-06 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('supplier', 'Supplier Payment'), ('staff', 'Staff Salary/Wages'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('other', 'Other Expense')], default='other', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='suppliers.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outgoing_payments_transactions',
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(fields=['user'], name='outgoing_pa_user_id_c4a420_idx'), models.Index(fields=['status'], name='outgoing_pa_status_9cb106_idx'), models.Index(fields=['payment_type'], name='outgoing_pa_payment_02973f_idx')],
            },
        ),
    ]
