# Generated by Django 4.2.16 on 2026-06-30 09:33

from django.db import migrations

CURRENCIES = [
    ('ZMW', 'Zambian Kwacha', 'ZK', True),
    ('USD', 'US Dollar', '$', False),
    ('EUR', 'Euro', '€', False),
    ('GBP', 'British Pound', '£', False),
    ('CNY', 'Chinese Yuan', '¥', False),
    ('ZAR', 'South African Rand', 'R', False),
    ('KES', 'Kenyan Shilling', 'KSh', False),
    ('NGN', 'Nigerian Naira', '₦', False),
    ('TZS', 'Tanzanian Shilling', 'TSh', False),
    ('UGX', 'Ugandan Shilling', 'USh', False),
    ('RWF', 'Rwandan Franc', 'FRw', False),
    ('MZN', 'Mozambican Metical', 'MT', False),
    ('BWP', 'Botswana Pula', 'P', False),
    ('AOA', 'Angolan Kwanza', 'Kz', False),
    ('MWK', 'Malawian Kwacha', 'MK', False),
]


def seed_currencies(apps, schema_editor):
    Currency = apps.get_model('currencies', 'Currency')
    for code, name, symbol, is_base in CURRENCIES:
        Currency.objects.get_or_create(
            code=code,
            defaults={'name': name, 'symbol': symbol, 'is_base': is_base}
        )


def reverse_seed(apps, schema_editor):
    Currency = apps.get_model('currencies', 'Currency')
    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_currencies, reverse_seed),
    ]
