# Generated by Django 4.2.16 on 2026-06-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_discount_amount_sale_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(default='ZMW', max_length=3),
        ),
    ]
