# Generated by Django 4.2.16 on 2026-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('voice', 'Voice Entry')], default='manual', max_length=10),
        ),
    ]
