# Generated by Django 4.2.7 on 2026-05-24 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('allowance', 'Allowance'), ('expense', 'Expense')], max_length=20)),
                ('category', models.CharField(choices=[('side_income', 'Side Income'), ('salary', 'Salary'), ('freelance', 'Freelance'), ('gift', 'Gift'), ('refund', 'Refund'), ('daily_allowance', 'Daily Allowance'), ('weekly_allowance', 'Weekly Allowance'), ('pocket_money', 'Pocket Money'), ('family_support', 'Family Support'), ('food', 'Food & Groceries'), ('transport', 'Transport'), ('airtime', 'Airtime & Data'), ('entertainment', 'Entertainment'), ('clothing', 'Clothing'), ('personal_care', 'Personal Care'), ('subscriptions', 'Subscriptions'), ('savings', 'Savings Transfer'), ('bills', 'Personal Bills'), ('other', 'Other')], default='other', max_length=50)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'transaction_type'], name='personal_tr_user_id_4e71ba_idx'), models.Index(fields=['user', 'date'], name='personal_tr_user_id_02dee6_idx'), models.Index(fields=['user', 'category'], name='personal_tr_user_id_17830d_idx')],
            },
        ),
    ]
