# Generated by Django 4.2.7 on 2026-06-06 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(help_text='Who is being paid', max_length=255)),
                ('payee_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('payee_email', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('supplier', 'Supplier / Stock Purchase'), ('salary', 'Salary / Wages'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('marketing', 'Marketing'), ('contractor', 'Contractor / Freelancer'), ('tax', 'Tax / Government'), ('loan_repayment', 'Loan Repayment'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=30)),
                ('reference_number', models.CharField(blank=True, help_text='Invoice / receipt / transaction ref', max_length=100, null=True)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outgoing_payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'payment_date'], name='outgoing_pa_user_id_3ace36_idx'), models.Index(fields=['category'], name='outgoing_pa_categor_2d8d83_idx')],
            },
        ),
    ]
