# Generated by Django 4.2.7 on 2026-06-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
    ]
